[project]
name = 'impact-x'
description = 'Cross-chain crowdfunding platform for Bitcoin builders'
authors = ['Impact-X Team']
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.campaign-registry]
path = 'contracts/campaign-registry.clar'
clarity_version = 3
epoch = '3.0'

[contracts.campaign-registry-v2]
path = 'contracts/campaign-registry-v2.clar'
clarity_version = 3
epoch = '3.0'

[repl.analysis]
passes = [
    'check_checker',
]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.settings]
format = 'legacy'
